name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USER }}/books-app:latest
      
    - name: deploying
      uses: appleboy/ssh-action@v0.1.4
      with:
          host: ${{ secrets.HETZNER_SERVER_IP }}
          username: ${{ secrets.HETZNER_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull DOCKER_USER/books-app:latest
            docker stop books-container || true
            docker rm books-container || true
            docker run -d --name books-container DOCKER_USER/books-app:latest
