name: Deploy to Hetzner

on:
  push:
    branches:
      - main  # Adjust if you want to trigger on different branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}

    - name: Copy files to Hetzner server
      run: |
        scp -o StrictHostKeyChecking=no -r . root@37.27.44.92:/root/my_project

    - name: Run books.js on Hetzner server
      run: |
        ssh -o StrictHostKeyChecking=no root@37.27.44.92 "node /root/my_project/books.js"
