# .github/workflows/deploy.yml
name: Deploy to Hetzner

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Deploy to Hetzner
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          ssh -o StrictHostKeyChecking=no root@128.140.104.144 "mkdir -p /var/www/books"
          rsync -avz --delete-after --exclude=node_modules ./ root@128.140.104.144 :/var/www/books/
          ssh root@128.140.104.144 "cd /var/www/books && npm install --production && pm2 restart all"  # Adjust to your server setup
