name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: ssh-keyscan ${{ secrets.HETZNER_SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Hetzner
      run: |
        ssh root@128.140.104.144 << 'EOF'
          if [ ! -d ".git" ]; then
            git init
            git remote add origin git@github.com:muradobied/postgres_test.git
          fi
          git fetch origin
          git reset --hard origin/main
          cd /root/my_project
          npm install
          if pm2 describe books > /dev/null; then
            pm2 restart books
          else
            pm2 start /root/my_project/books.js --name books
          fi
        EOF
    # git pull origin main
