name: Deploy to Hetzner

on:
  push:
    branches:
      - main  # Adjust if you want to trigger on different branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}

    - name: Copy files to Hetzner server
      run: |
        scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.HETZNER_SERVER_USER }}@${{ secrets.HETZNER_SERVER_IP }}:/root/my_project

    - name: Run books.js on Hetzner server
      run: |
        ssh ${{ secrets.HETZNER_SERVER_USER }}@${{ secrets.HETZNER_SERVER_IP }} 'bash -s' < ./deploy.sh
