name: Build and Deploy Docker Image #on hetzner training-devops server

on:
  push:
    branches:
      - main #selecting the main branch on github repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  #checking the code syntax 
      uses: actions/checkout@v3
      

  deploy:  #deploying the image from dockerhub to the hetzner server
    runs-on: ubuntu-latest
    steps:
    - name: Setup The CI/CD
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        #port: 22
        script: | #the script to run the docker image on the hetzner server
          set -exu
          cd /root/backend/postgres_test
          git pull origin main
          docker build -f Dockerfile . -t books-app:${{ github.sha }} \
          --build-arg="booksServer=172.17.0.1" \
          docker stop books-container || true
          docker rm books-container || true
          docker run -d --name books-container books-app:${{ github.sha }}
          docker image prune -a -f
